# Generated by Django 3.0.5 on 2020-12-31 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='virus_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcip', models.IntegerField(max_length=16, verbose_name='IP地址')),
                ('username', models.IntegerField(max_length=64, verbose_name='姓名')),
                ('number', models.IntegerField(max_length=64, verbose_name='编号')),
                ('pcname', models.IntegerField(max_length=64, verbose_name='计算机名')),
                ('status', models.IntegerField(max_length=16, verbose_name='处理情况')),
                ('handle_time', models.DateField(default=datetime.datetime(2020, 12, 31, 11, 47, 0, 182020), verbose_name='处理时间')),
                ('remarks', models.IntegerField(max_length=128, verbose_name='备注')),
                ('virus_type', models.IntegerField(max_length=128, verbose_name='病毒种类')),
                ('pcmac', models.IntegerField(max_length=64, verbose_name='MAC')),
            ],
        ),
    ]
