# Generated by Django 3.0.5 on 2020-12-31 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0002_auto_20201231_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virus_record',
            name='handle_time',
            field=models.DateField(default=datetime.datetime(2020, 12, 31, 11, 47, 51, 461147), verbose_name='处理时间'),
        ),
    ]
