# Generated by Django 3.0.5 on 2020-12-31 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0003_auto_20201231_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virus_record',
            name='handle_time',
            field=models.DateField(default=datetime.datetime(2020, 12, 31, 11, 48, 57, 885789), verbose_name='处理时间'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='number',
            field=models.IntegerField(verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='pcip',
            field=models.IntegerField(verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='pcmac',
            field=models.IntegerField(verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='pcname',
            field=models.IntegerField(verbose_name='计算机名'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='remarks',
            field=models.IntegerField(verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='status',
            field=models.IntegerField(verbose_name='处理情况'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='username',
            field=models.IntegerField(verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='virus_type',
            field=models.IntegerField(verbose_name='病毒种类'),
        ),
    ]
