# Generated by Django 3.0.5 on 2020-12-31 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0004_auto_20201231_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virus_record',
            name='handle_time',
            field=models.DateField(default=datetime.datetime(2020, 12, 31, 16, 11, 44, 56848), verbose_name='处理时间'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='virus_type',
            field=models.IntegerField(default='挖矿病毒', verbose_name='病毒种类'),
        ),
    ]
