# Generated by Django 3.0.5 on 2020-12-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0005_auto_20201231_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virus_record',
            name='handle_time',
            field=models.DateField(verbose_name='处理时间'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='number',
            field=models.TextField(verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='pcip',
            field=models.CharField(max_length=128, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='pcmac',
            field=models.TextField(verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='pcname',
            field=models.TextField(verbose_name='计算机名'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='remarks',
            field=models.TextField(verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='status',
            field=models.TextField(verbose_name='处理情况'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='username',
            field=models.TextField(verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='virus_type',
            field=models.TextField(verbose_name='病毒种类'),
        ),
    ]
