# Generated by Django 3.0.5 on 2021-01-04 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0007_auto_20201231_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virus_record',
            options={'verbose_name': '病毒记录表', 'verbose_name_plural': '病毒记录表'},
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='handle_time',
            field=models.DateField(blank=True, null=True, verbose_name='处理时间'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='number',
            field=models.TextField(blank=True, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='pcip',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='pcmac',
            field=models.TextField(blank=True, null=True, verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='pcname',
            field=models.TextField(blank=True, null=True, verbose_name='计算机名'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='status',
            field=models.TextField(blank=True, null=True, verbose_name='处理情况'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='username',
            field=models.TextField(blank=True, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='virus_type',
            field=models.TextField(blank=True, null=True, verbose_name='病毒种类'),
        ),
        migrations.CreateModel(
            name='mail_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usermail', models.TextField(max_length=200, verbose_name='邮箱')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virus.virus_record', verbose_name='姓名')),
            ],
            options={
                'verbose_name': '用户邮箱表',
                'verbose_name_plural': '用户邮箱表',
            },
        ),
    ]
