# Generated by Django 3.0.5 on 2021-01-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0008_auto_20210104_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virus_record',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='virus_type',
            field=models.TextField(blank=True, default='挖矿病毒', null=True, verbose_name='病毒种类'),
        ),
    ]
