# Generated by Django 3.0.5 on 2021-02-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0009_auto_20210104_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complete', models.TextField(blank=True, null=True, verbose_name='是否完成')),
                ('Source', models.TextField(blank=True, max_length=30, null=True, verbose_name='需求来源')),
                ('Document_No', models.TextField(blank=True, max_length=50, null=True, verbose_name='单据号')),
                ('Order_No', models.TextField(blank=True, max_length=50, null=True, verbose_name='采购订单号')),
                ('Requisition_date', models.DateField(blank=True, null=True, verbose_name='请购日期')),
                ('Materials', models.TextField(blank=True, max_length=300, null=True, verbose_name='请购物资/固定资产')),
                ('Department', models.TextField(blank=True, max_length=50, null=True, verbose_name='请购部门')),
                ('Requisitioner', models.TextField(blank=True, max_length=30, null=True, verbose_name='请购人')),
                ('Requisition_Num', models.CharField(blank=True, max_length=20, null=True, verbose_name='请购数量')),
                ('Requisition_purpose', models.TextField(blank=True, max_length=300, null=True, verbose_name='请购用途')),
                ('Order_Time', models.DateField(blank=True, null=True, verbose_name='采购订单生成时间')),
                ('Purchaser', models.TextField(blank=True, max_length=30, null=True, verbose_name='采购员')),
                ('Reason', models.TextField(blank=True, max_length=300, null=True, verbose_name='超长原因说明')),
                ('Supplier', models.TextField(blank=True, max_length=100, null=True, verbose_name='供应商')),
                ('Arrival_time1', models.DateField(blank=True, null=True, verbose_name='预计到货时间（采购回复）')),
                ('Arrival_time2', models.DateField(blank=True, null=True, verbose_name='预计到货时间（供应商回复）')),
                ('Actual_time1', models.DateField(blank=True, null=True, verbose_name='实际到货时间（一）')),
                ('Actual_Num1', models.CharField(blank=True, max_length=20, null=True, verbose_name='实际到货数量（一）')),
                ('Actual_time2', models.DateField(blank=True, null=True, verbose_name='实际到货时间（二）')),
                ('Actual_Num2', models.CharField(blank=True, max_length=20, null=True, verbose_name='实际到货数量（二）')),
                ('Actual_time3', models.DateField(blank=True, null=True, verbose_name='实际到货时间（三）')),
                ('Actual_Num3', models.CharField(blank=True, max_length=20, null=True, verbose_name='实际到货数量（三）')),
                ('Unarrival_Num', models.CharField(blank=True, max_length=20, null=True, verbose_name='未到数量')),
                ('Overdue', models.TextField(blank=True, null=True, verbose_name='是否超期')),
                ('Overdue_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='超期时间')),
                ('Remarks', models.TextField(blank=True, max_length=300, null=True, verbose_name='备注')),
            ],
        ),
        migrations.AlterField(
            model_name='mail_info',
            name='usermail',
            field=models.TextField(max_length=100, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='number',
            field=models.TextField(blank=True, max_length=30, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='pcmac',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='pcname',
            field=models.TextField(blank=True, max_length=30, null=True, verbose_name='计算机名'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='remarks',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='username',
            field=models.TextField(blank=True, max_length=30, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='virus_record',
            name='virus_type',
            field=models.TextField(blank=True, default='挖矿病毒', max_length=100, null=True, verbose_name='病毒种类'),
        ),
    ]
