# Generated by Django 3.0.5 on 2021-02-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0010_auto_20210204_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='Complete',
            new_name='Finish',
        ),
    ]
