# Generated by Django 3.0.5 on 2021-02-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0011_auto_20210204_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
    ]
