# Generated by Django 3.0.5 on 2021-02-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0013_auto_20210218_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='c_time',
        ),
        migrations.AddField(
            model_name='user',
            name='jobnum',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
    ]
