# Generated by Django 3.0.5 on 2021-02-18 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0014_auto_20210218_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['c_time'], 'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AddField(
            model_name='user',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
